// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netCore.Data;

namespace netCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("netCore.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Kada")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ko")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("netCore.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("kome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("poruka")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationID");

                    b.ToTable("Notif");
                });
#pragma warning restore 612, 618
        }
    }
}
